name: batman
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0
  dio: ^5.4.1
  stacked: ^3.4.2
  flutter_native_splash: ^2.4.0
  avatar_view: ^1.0.1
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  android : true,
  ios : true,
  web : false

color: "#FFCC00"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
     - family: RegularFont
       fonts:
         - asset: assets/fonts/Mulish-Regular.ttf
     - family: MediumFont
       fonts:
         - asset: assets/fonts/Mulish-Bold.ttf